name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akinus21/rust-ci:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Build binary
        run: |
          cargo build --release
          ls -la target/release/anvil
