name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akinus21/rust-ci:latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release
        run: |
          cargo build --release
          tar -czvf anvil.tar.gz target/release/anvil

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: anvil.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
